### ISSUE TITLE
Can't download some files

### ISSUE THREAD

**Issue by educ8s** [abdlalisalmi/wistia-downloader#4]
I downloaded some files just fine, but for some I get the following error:

Traceback (most recent call last):
  File ".\wistia-downloader.py", line 210, in <module>
    main()
  File ".\wistia-downloader.py", line 201, in main
    local_filename, resolution)
  File ".\wistia-downloader.py", line 49, in html_page_handle_and_download
    for con in file:
  File "C:\Users\Nikos\AppData\Local\Programs\Python\Python36\lib\encodings\cp1253.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 178: character maps to <undefined>

What do you think is wrong here?

**Comment by educ8s** [comment]
Ok, I found a workaround

Change line 42 of the command line script to this:

    with open(file_name, "r", errors='ignore') as file:

The script has problem recognizing video titles in Greek language in my case.
